version: '3'
services:
   account-service:
      build: ./AccountService
      ports:
         - "8000:8000"
      environment:
         - SPRING_DATA_MONGODB_HOST=mongodb
      depends_on:
         - mongodb
   mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null   